from __future__ import annotations

import os
from typing import Dict, Optional, Tuple

from .sexpr import Node, Sym, dumps, loads, num

# finished hole -> the metric screw KiCad names the footprint after
MOUNTING_HOLES: Dict[float, str] = {
    2.2: "M2", 3.2: "M3", 4.3: "M4", 5.3: "M5", 6.4: "M6", 8.4: "M8",
}

_SEARCH = (
    os.environ.get("KICAD10_FOOTPRINT_DIR"),
    os.environ.get("KICAD9_FOOTPRINT_DIR"),
    os.environ.get("KICAD_FOOTPRINT_DIR"),
    "/Applications/KiCad/KiCad.app/Contents/SharedSupport/footprints",
    "/usr/share/kicad/footprints",
    "/usr/local/share/kicad/footprints",
    "C:/Program Files/KiCad/share/kicad/footprints",
)


def library_root() -> Optional[str]:
    for candidate in _SEARCH:
        if candidate and os.path.isdir(candidate):
            return candidate
    return None


def _mm(value: float) -> str:
    return ("%.2f" % value).rstrip("0").rstrip(".")


def mounting_hole_name(drill_mm: float) -> Optional[str]:
    screw = MOUNTING_HOLES.get(round(drill_mm, 2))
    if screw is None:
        return None
    return "MountingHole_%smm_%s" % (_mm(drill_mm), screw)


def _read_stock(name: str) -> Optional[str]:
    root = library_root()
    if root is None:
        return None
    path = os.path.join(root, "MountingHole.pretty", "%s.kicad_mod" % name)
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return None


def _rebuild(name: str, drill_mm: float, screw: str) -> str:
    text_y = drill_mm + 0.95
    font = ["effects", ["font", ["size", num(1), num(1)],
                        ["thickness", num(0.15)]]]
    node: Node = [
        "footprint", name,
        ["version", Sym("20260206")],
        ["generator", "kicad-footprint-generator"],
        ["layer", "F.Cu"],
        ["descr", "Mounting Hole %smm, %s, no annular, generated by "
                  "kicad-footprint-generator mountinghole.py"
                  % (_mm(drill_mm), screw)],
        ["tags", "mountinghole %s" % screw],
        ["property", "Reference", "REF**",
         ["at", num(0), num(-text_y), num(0)], ["layer", "F.SilkS"], font],
        ["property", "Value", name,
         ["at", num(0), num(text_y), num(0)], ["layer", "F.Fab"], font],
        ["attr", Sym("exclude_from_pos_files"), Sym("exclude_from_bom")],
        ["fp_circle",
         ["center", num(0), num(0)], ["end", num(drill_mm), num(0)],
         ["stroke", ["width", num(0.15)], ["type", Sym("solid")]],
         ["fill", Sym("no")], ["layer", "Cmts.User"]],
        ["fp_circle", ["center", num(0), num(0)],
         ["end", num(drill_mm + 0.25), num(0)],
         ["stroke", ["width", num(0.05)], ["type", Sym("solid")]],
         ["fill", Sym("no")], ["layer", "F.CrtYd"]],
        ["fp_text", Sym("user"), "${REFERENCE}",
         ["at", num(0), num(0), num(0)], ["layer", "F.Fab"], font],
        ["pad", "", Sym("np_thru_hole"), Sym("circle"),
         ["at", num(0), num(0)],
         ["size", num(drill_mm), num(drill_mm)],
         ["drill", num(drill_mm)],
         ["layers", "*.Cu", "*.Mask"]],
        ["embedded_fonts", Sym("no")],
    ]
    return dumps(node) + "\n"


def mounting_hole(drill_mm: float) -> Optional[Tuple[str, Node, bool]]:
    name = mounting_hole_name(drill_mm)
    if name is None:
        return None
    text = _read_stock(name)
    from_kicad = text is not None
    if text is None:
        text = _rebuild(name, drill_mm, MOUNTING_HOLES[round(drill_mm, 2)])
    return ("MountingHole:%s" % name, loads(text), from_kicad)
